Repository VernonHawk/MyLibrary, pull requests merged in 2019-03, with the labels that each got.

#1 README and gitignore minor updates
  .gitignore
  README.md
Labels: enhancement

#2 Implemented Landing page
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ukma/mylibrary/MainActivity.java
  app/src/main/java/com/ukma/mylibrary/Role.java
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#4 Update README
  README.md
Labels: good first issue

#5 Sign In/Up basic logic
  .gitignore
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/java/com/ukma/mylibrary/SignUpActivity.java
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement, good first issue

#6 TextInputLayouts + Phone number misc
  app/build.gradle
  app/src/main/java/com/ukma/mylibrary/PhoneNumberHelper.java
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/java/com/ukma/mylibrary/SignUpActivity.java
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#8 Auth functionality + Entity serialization/deserialization
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ukma/mylibrary/MainActivity.java
  app/src/main/java/com/ukma/mylibrary/Role.java
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/java/com/ukma/mylibrary/SignUpActivity.java
  app/src/main/java/com/ukma/mylibrary/Tools/JWTHeaderHelper.java
  app/src/main/java/com/ukma/mylibrary/Tools/PhoneNumberHelper.java
  app/src/main/java/com/ukma/mylibrary/api/API.java
  app/src/main/java/com/ukma/mylibrary/api/APIJsonArrayRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIJsonObjectRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIRequestNoListenerSpecifiedException.java
  app/src/main/java/com/ukma/mylibrary/api/APIResponse.java
  app/src/main/java/com/ukma/mylibrary/api/APIRoutes.java
  app/src/main/java/com/ukma/mylibrary/api/Route.java
  app/src/main/java/com/ukma/mylibrary/entities/Entity.java
  app/src/main/java/com/ukma/mylibrary/entities/Role.java
  app/src/main/java/com/ukma/mylibrary/entities/User.java
  app/src/main/java/com/ukma/mylibrary/entities/factory/EntityFactory.java
  app/src/main/java/com/ukma/mylibrary/entities/factory/EntityJSONFactory.java
  app/src/main/java/com/ukma/mylibrary/entities/factory/IEntityFactory.java
  app/src/main/java/com/ukma/mylibrary/entities/factory/IEntityJSONFactory.java
  app/src/main/java/com/ukma/mylibrary/entities/filters/EmptyIdFilter.java
  app/src/main/java/com/ukma/mylibrary/managers/AuthManager.java
  app/src/main/java/com/ukma/mylibrary/managers/RequestQueueManager.java
  app/src/main/res/layout/activity_sign_up.xml
  app/src/test/java/com/ukma/mylibrary/entities/factory/EntityFactoryTest.java
  app/src/test/java/com/ukma/mylibrary/entities/factory/EntityJSONFactoryTest.java
Labels: enhancement

#7 Add reader cabinet with Actual page and basic logic
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/ActualReaderAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/ItemUtils.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibraryAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/ReservedReaderAdapter.java
  app/src/main/java/com/ukma/mylibrary/components/AbstractReaderItem.java
  app/src/main/java/com/ukma/mylibrary/components/ActualReaderItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibraryItem.java
  app/src/main/java/com/ukma/mylibrary/components/ReservedReaderItem.java
  app/src/main/res/drawable/ic_account_box_black_24dp.xml
  app/src/main/res/drawable/ic_bookmark_black_24dp.xml
  app/src/main/res/drawable/ic_collections_bookmark_black_24dp.xml
  app/src/main/res/drawable/ic_info_outline_black_24dp.xml
  app/src/main/res/drawable/ic_local_library_black_24dp.xml
  app/src/main/res/drawable/radiobtn_out_line.xml
  app/src/main/res/drawable/toggle_widget_background.xml
  app/src/main/res/layout/activity_reader_library.xml
  app/src/main/res/layout/activity_reader_orders.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/list_item_actual.xml
  app/src/main/res/layout/list_item_library.xml
  app/src/main/res/layout/list_item_reserved.xml
  app/src/main/res/menu/reader_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, help wanted

#10 Client Authorization connected with server
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/SignInActivity.java
  app/src/main/java/com/ukma/mylibrary/SignUpActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarActivity.java
  app/src/main/java/com/ukma/mylibrary/api/APIJsonArrayRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIJsonObjectRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIRequest.java
  app/src/main/java/com/ukma/mylibrary/api/APIResponse.java
  app/src/main/java/com/ukma/mylibrary/api/APIRoutes.java
  app/src/main/java/com/ukma/mylibrary/managers/AuthManager.java
  app/src/main/java/com/ukma/mylibrary/tools/InputValidator.java
  app/src/main/java/com/ukma/mylibrary/tools/JWTHeaderHelper.java
  app/src/main/java/com/ukma/mylibrary/tools/PhoneNumberHelper.java
  app/src/main/java/com/ukma/mylibrary/tools/ToastHelper.java
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, good first issue
