Repository VernonHawk/MyLibrary, pull requests merged in 2019-04, with the labels that each got.

#14 Loading username in a personal cabinet
  app/src/main/java/com/ukma/mylibrary/LibrarianMainActivity.java
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarLibrarianActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianAdapter.java
  app/src/main/java/com/ukma/mylibrary/entities/Role.java
  app/src/main/res/layout/activity_librarian_layout.xml
  app/src/main/res/values/strings.xml
Labels: good first issue

#13 Order and issues server link
  .gitignore
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/ActualReaderAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibraryAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/ReservedReaderAdapter.java
  app/src/main/java/com/ukma/mylibrary/api/API.java
  app/src/main/java/com/ukma/mylibrary/api/APIRoutes.java
  app/src/main/java/com/ukma/mylibrary/api/Route.java
  app/src/main/java/com/ukma/mylibrary/components/ActualReaderItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibraryItem.java
  app/src/main/java/com/ukma/mylibrary/components/ReservedReaderItem.java
  app/src/main/java/com/ukma/mylibrary/entities/CopyIssue.java
  app/src/main/java/com/ukma/mylibrary/entities/SciPubCopy.java
  app/src/main/java/com/ukma/mylibrary/entities/SciPubOrder.java
  app/src/main/java/com/ukma/mylibrary/entities/ScientificPublication.java
  app/src/main/res/layout/activity_reader_library.xml
  app/src/main/res/layout/list_item_actual.xml
  app/src/main/res/layout/list_item_library.xml
  app/src/main/res/layout/list_item_reserved.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#15 Sign Out rework
  app/src/main/java/com/ukma/mylibrary/LibrarianMainActivity.java
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarActivity.java
  app/src/main/java/com/ukma/mylibrary/ToolbarReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/managers/AuthManager.java
  app/src/main/res/layout/activity_librarian_userlist.xml
Labels: good first issue

#16 Librarian load readers
  app/src/main/java/com/ukma/mylibrary/LibrarianActionActivity.java
  app/src/main/java/com/ukma/mylibrary/LibrarianMainActivity.java
  app/src/main/java/com/ukma/mylibrary/LibraryActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianAdapter.java
  app/src/main/java/com/ukma/mylibrary/api/APIRoutes.java
  app/src/main/java/com/ukma/mylibrary/api/Route.java
  app/src/main/java/com/ukma/mylibrary/components/AbstractItem.java
  app/src/main/java/com/ukma/mylibrary/components/ActualReaderItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianReturnItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianWithdrawalItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibraryItem.java
  app/src/main/java/com/ukma/mylibrary/components/ReservedReaderItem.java
  app/src/main/res/layout/activity_librarian_action.xml
  app/src/main/res/layout/activity_librarian_userlist.xml
  app/src/main/res/layout/activity_reader_library.xml
  app/src/main/res/layout/list_librarian_return.xml
  app/src/main/res/layout/list_librarian_withdrawal.xml
  app/src/main/res/layout/list_readers.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#18 Reader acceptance test
  .gitignore
  .idea/codeStyles/Project.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  app/build.gradle
  app/src/androidTest/java/com/ukma/mylibrary/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/ukma/mylibrary/ReaderAcceptanceTest.java
  app/src/androidTest/java/com/ukma/mylibrary/helpers/TestsHelper.java
  app/src/androidTest/java/com/ukma/mylibrary/helpers/ViewActions.java
  app/src/androidTest/java/com/ukma/mylibrary/matchers/LibraryItemMatchers.java
  app/src/androidTest/java/com/ukma/mylibrary/matchers/ReservedReaderItemMatchers.java
  app/src/test/java/com/ukma/mylibrary/ExampleUnitTest.java
  app/src/test/java/com/ukma/mylibrary/entities/factory/EntityFactoryTest.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: good first issue

#17 Implemented full Librarian logic
  app/src/main/java/com/ukma/mylibrary/LibrarianActionActivity.java
  app/src/main/java/com/ukma/mylibrary/LibrarianMainActivity.java
  app/src/main/java/com/ukma/mylibrary/MainActivity.java
  app/src/main/java/com/ukma/mylibrary/ReaderActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/ActualReaderAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/ItemUtils.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianReturnAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianWithdrawalAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibraryAdapter.java
  app/src/main/java/com/ukma/mylibrary/api/APIRoutes.java
  app/src/main/java/com/ukma/mylibrary/api/Route.java
  app/src/main/java/com/ukma/mylibrary/components/ActualReaderItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianReturnItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianWithdrawalItem.java
  app/src/main/java/com/ukma/mylibrary/components/LibraryItem.java
  app/src/main/java/com/ukma/mylibrary/entities/CopyIssue.java
  app/src/main/java/com/ukma/mylibrary/entities/User.java
  app/src/main/java/com/ukma/mylibrary/tools/Fetcher.java
  app/src/main/java/com/ukma/mylibrary/tools/ItemUtils.java
  app/src/main/res/drawable/ic_local_library_black_24dp.xml
  app/src/main/res/layout/activity_librarian_action.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/list_item_actual.xml
  app/src/main/res/layout/list_librarian_return.xml
  app/src/main/res/layout/list_librarian_withdrawal.xml
  app/src/main/res/layout/list_readers.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#20 Librarian acceptance test
  app/src/androidTest/java/com/ukma/mylibrary/LibrarianAcceptanceTest.java
  app/src/androidTest/java/com/ukma/mylibrary/ReaderAcceptanceTest.java
  app/src/androidTest/java/com/ukma/mylibrary/matchers/LibrarianItemMatchers.java
  app/src/androidTest/java/com/ukma/mylibrary/matchers/LibrarianReturnItemMatchers.java
  app/src/androidTest/java/com/ukma/mylibrary/matchers/LibrarianWithdrawalItemMatchers.java
  app/src/main/java/com/ukma/mylibrary/LibrarianActionActivity.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibrarianAdapter.java
  app/src/main/java/com/ukma/mylibrary/adapters/LibraryAdapter.java
  app/src/main/java/com/ukma/mylibrary/components/LibrarianItem.java
  app/src/main/java/com/ukma/mylibrary/entities/User.java
  app/src/main/java/com/ukma/mylibrary/tools/Fetcher.java
  app/src/main/res/values/strings.xml
Labels: enhancement, good first issue
